// بيانات وهمية للتجربة
export const sampleBookings = [
  {
    id: '1',
    bookingNumber: 'BK-2025-001',
    guestId: 'guest-1',
    guestName: 'أحمد محمد علي',
    roomId: 'room-101',
    roomName: '101',
    status: 'قائمة' as const,
    source: 'موقع_الكتروني' as const,
    checkInDate: '18-10-2025',
    checkOutDate: '22-10-2025',
    nights: 4,
    basePrice: 300,
    totalPrice: 1200,
    paidAmount: 600,
    remainingBalance: 600,
    paymentStatus: 'جزئي' as const,
    paymentMethod: 'نقد' as const,
    numberOfGuests: 2,
    childrenCount: 1,
    specialRequests: 'غرفة بإطلالة على البحر',
    createdAt: '15-10-2025',
    updatedAt: '15-10-2025'
  },
  {
    id: '2',
    bookingNumber: 'BK-2025-002',
    guestId: 'guest-2',
    guestName: 'فاطمة حسن',
    roomId: 'room-102',
    roomName: '102',
    status: 'جاهز_دخول' as const,
    source: 'هاتف' as const,
    checkInDate: '19-10-2025',
    checkOutDate: '24-10-2025',
    nights: 5,
    basePrice: 350,
    totalPrice: 1750,
    paidAmount: 1750,
    remainingBalance: 0,
    paymentStatus: 'مكتمل' as const,
    paymentMethod: 'بطاقة' as const,
    numberOfGuests: 3,
    childrenCount: 0,
    specialRequests: 'سرير إضافي',
    createdAt: '16-10-2025',
    updatedAt: '18-10-2025'
  },
  {
    id: '3',
    bookingNumber: 'BK-2025-003',
    guestId: 'guest-3',
    guestName: 'خالد عبدالله',
    roomId: 'room-103',
    roomName: '103',
    status: 'قادمة' as const,
    source: 'وكيل' as const,
    checkInDate: '25-10-2025',
    checkOutDate: '30-10-2025',
    nights: 5,
    basePrice: 400,
    totalPrice: 2000,
    paidAmount: 500,
    remainingBalance: 1500,
    paymentStatus: 'دفعة_مقدمة' as const,
    paymentMethod: 'تحويل' as const,
    numberOfGuests: 2,
    specialRequests: '',
    createdAt: '17-10-2025',
    updatedAt: '17-10-2025',
    companyName: 'شركة السفر الذهبي',
    companyTaxId: '123456789'
  },
  {
    id: '4',
    bookingNumber: 'BK-2025-004',
    guestId: 'guest-4',
    guestName: 'مريم عبدالرحمن',
    roomId: 'room-201',
    roomName: '201',
    status: 'قائمة' as const,
    source: 'موقع_الكتروني' as const,
    checkInDate: '20-10-2025',
    checkOutDate: '23-10-2025',
    nights: 3,
    basePrice: 450,
    totalPrice: 1350,
    paidAmount: 1350,
    remainingBalance: 0,
    paymentStatus: 'مكتمل' as const,
    paymentMethod: 'بطاقة' as const,
    numberOfGuests: 1,
    childrenCount: 0,
    specialRequests: 'غرفة هادئة بعيدة عن المصعد',
    createdAt: '18-10-2025',
    updatedAt: '18-10-2025'
  },
  {
    id: '5',
    bookingNumber: 'BK-2025-005',
    guestId: 'guest-5',
    guestName: 'عمر سعيد',
    roomId: 'room-202',
    roomName: '202',
    status: 'جاهز_خروج' as const,
    source: 'هاتف' as const,
    checkInDate: '15-10-2025',
    checkOutDate: '20-10-2025',
    nights: 5,
    basePrice: 320,
    totalPrice: 1600,
    paidAmount: 1600,
    remainingBalance: 0,
    paymentStatus: 'مكتمل' as const,
    paymentMethod: 'نقد' as const,
    numberOfGuests: 4,
    childrenCount: 2,
    specialRequests: 'سريران إضافيان للأطفال',
    createdAt: '10-10-2025',
    updatedAt: '15-10-2025'
  },
  {
    id: '6',
    bookingNumber: 'BK-2025-006',
    guestId: 'guest-6',
    guestName: 'ليلى محمود',
    roomId: 'room-0101',
    roomName: '0101',
    status: 'قائمة' as const,
    source: 'موقع_الكتروني' as const,
    checkInDate: '18-10-2025',
    checkOutDate: '25-10-2025',
    nights: 7,
    basePrice: 500,
    totalPrice: 3500,
    paidAmount: 1000,
    remainingBalance: 2500,
    paymentStatus: 'دفعة_مقدمة' as const,
    paymentMethod: 'تحويل' as const,
    numberOfGuests: 2,
    childrenCount: 0,
    specialRequests: 'أثاث عصري',
    createdAt: '12-10-2025',
    updatedAt: '12-10-2025'
  },
  {
    id: '7',
    bookingNumber: 'BK-2025-007',
    guestId: 'guest-7',
    guestName: 'يوسف إبراهيم',
    roomId: 'room-301',
    roomName: '301',
    status: 'غير مؤكدة' as const,
    source: 'واتساب' as const,
    checkInDate: '22-10-2025',
    checkOutDate: '27-10-2025',
    nights: 5,
    basePrice: 380,
    totalPrice: 1900,
    paidAmount: 0,
    remainingBalance: 1900,
    paymentStatus: 'غير_مدفوع' as const,
    numberOfGuests: 3,
    childrenCount: 1,
    specialRequests: '',
    createdAt: '19-10-2025',
    updatedAt: '19-10-2025'
  },
  {
    id: '8',
    bookingNumber: 'BK-2025-008',
    guestId: 'guest-8',
    guestName: 'سارة أحمد',
    roomId: 'room-302',
    roomName: '302',
    status: 'قائمة' as const,
    source: 'هاتف' as const,
    checkInDate: '21-10-2025',
    checkOutDate: '26-10-2025',
    nights: 5,
    basePrice: 420,
    totalPrice: 2100,
    paidAmount: 2100,
    remainingBalance: 0,
    paymentStatus: 'مكتمل' as const,
    paymentMethod: 'بطاقة' as const,
    numberOfGuests: 2,
    childrenCount: 0,
    specialRequests: 'ميني بار',
    createdAt: '19-10-2025',
    updatedAt: '19-10-2025'
  },
  {
    id: '9',
    bookingNumber: 'BK-2025-009',
    guestId: 'guest-9',
    guestName: 'محمد عبدالعزيز',
    roomId: 'room-66',
    roomName: '66',
    status: 'قادمة' as const,
    source: 'موقع_الكتروني' as const,
    checkInDate: '28-10-2025',
    checkOutDate: '02-11-2025',
    nights: 5,
    basePrice: 360,
    totalPrice: 1800,
    paidAmount: 900,
    remainingBalance: 900,
    paymentStatus: 'جزئي' as const,
    paymentMethod: 'نقد' as const,
    numberOfGuests: 2,
    childrenCount: 0,
    specialRequests: '',
    createdAt: '18-10-2025',
    updatedAt: '18-10-2025'
  },
  {
    id: '10',
    bookingNumber: 'BK-2025-010',
    guestId: 'guest-10',
    guestName: 'نورا حسين',
    roomId: 'room-401',
    roomName: '401',
    status: 'قائمة' as const,
    source: 'وكيل' as const,
    checkInDate: '19-10-2025',
    checkOutDate: '22-10-2025',
    nights: 3,
    basePrice: 390,
    totalPrice: 1170,
    paidAmount: 1170,
    remainingBalance: 0,
    paymentStatus: 'مكتمل' as const,
    paymentMethod: 'شيك' as const,
    numberOfGuests: 1,
    childrenCount: 0,
    specialRequests: 'طابق هادئ',
    createdAt: '17-10-2025',
    updatedAt: '17-10-2025',
    companyName: 'وكالة النجوم للسياحة'
  }
];

// موظفين وهميين
export const sampleEmployees = [
  {
    id: 'emp-1',
    name: 'أحمد محمد',
    role: 'مدير الاستقبال',
    phone: '01012345678',
    email: 'ahmed@almodif.com',
    avatar: '',
    status: 'متاح',
    department: 'الاستقبال',
    joinDate: '01-01-2024'
  },
  {
    id: 'emp-2',
    name: 'فاطمة حسن',
    role: 'موظفة استقبال',
    phone: '01112345678',
    email: 'fatma@almodif.com',
    avatar: '',
    status: 'متاح',
    department: 'الاستقبال',
    joinDate: '15-02-2024'
  },
  {
    id: 'emp-3',
    name: 'محمد علي',
    role: 'مدير المبيعات',
    phone: '01212345678',
    email: 'mohamed@almodif.com',
    avatar: '',
    status: 'مشغول',
    department: 'المبيعات',
    joinDate: '10-03-2024'
  },
  {
    id: 'emp-4',
    name: 'سارة أحمد',
    role: 'خدمة العملاء',
    phone: '01512345678',
    email: 'sarah@almodif.com',
    avatar: '',
    status: 'متاح',
    department: 'خدمة العملاء',
    joinDate: '20-04-2024'
  },
  {
    id: 'emp-5',
    name: 'خالد عبدالله',
    role: 'مشرف الصيانة',
    phone: '01612345678',
    email: 'khaled@almodif.com',
    avatar: '',
    status: 'في إجازة',
    department: 'الصيانة',
    joinDate: '05-05-2024'
  },
  {
    id: 'emp-6',
    name: 'نور الهدى',
    role: 'موظفة حسابات',
    phone: '01712345678',
    email: 'nour@almodif.com',
    avatar: '',
    status: 'متاح',
    department: 'المحاسبة',
    joinDate: '12-06-2024'
  },
  {
    id: 'emp-7',
    name: 'عمر سعيد',
    role: 'موظف أمن',
    phone: '01812345678',
    email: 'omar@almodif.com',
    avatar: '',
    status: 'متاح',
    department: 'الأمن',
    joinDate: '25-07-2024'
  },
  {
    id: 'emp-8',
    name: 'مريم يوسف',
    role: 'مديرة التسويق',
    phone: '01912345678',
    email: 'mariam@almodif.com',
    avatar: '',
    status: 'مشغول',
    department: 'التسويق',
    joinDate: '08-08-2024'
  }
];

// محادثات وهمية
export const sampleConversations = [
  {
    id: 'conv-1',
    employeeId: 'emp-1',
    employeeName: 'أحمد محمد',
    lastMessage: 'مرحباً، كيف يمكنني مساعدتك؟',
    lastMessageTime: '10:30 ص',
    unreadCount: 0,
    status: 'متاح',
    avatar: ''
  },
  {
    id: 'conv-2',
    employeeId: 'emp-2',
    employeeName: 'فاطمة حسن',
    lastMessage: 'تم تأكيد الحجز بنجاح',
    lastMessageTime: '09:15 ص',
    unreadCount: 2,
    status: 'متاح',
    avatar: ''
  },
  {
    id: 'conv-3',
    employeeId: 'emp-3',
    employeeName: 'محمد علي',
    lastMessage: 'سأتواصل معك قريباً',
    lastMessageTime: 'أمس',
    unreadCount: 0,
    status: 'مشغول',
    avatar: ''
  },
  {
    id: 'conv-4',
    employeeId: 'emp-4',
    employeeName: 'سارة أحمد',
    lastMessage: 'شكراً لتواصلك معنا',
    lastMessageTime: 'أمس',
    unreadCount: 1,
    status: 'متاح',
    avatar: ''
  },
  {
    id: 'conv-5',
    employeeId: 'emp-6',
    employeeName: 'نور الهدى',
    lastMessage: 'تم إصدار الفاتورة',
    lastMessageTime: '08:45 ص',
    unreadCount: 0,
    status: 'متاح',
    avatar: ''
  }
];
